### PR TITLE
Merge recent updates

### PR DESCRIPTION
**Pull request by joshiayush**

### CODE REVIEW

**Comment by joshiayush** [comment]
Hello, lately you've been contributing to the "stlc" project which is quite
helpful for me. I visited some of your repositories and found that you
possess good knowledge of C programming language and I found your
"cepresso" framework amazing. I just wanted to know if you are going to
continue contributing to the "stlc" project? Because I wanted a way to
generate documents for "stlc" library from the docstrings that I've put
over each functional API inside "stlc" so if you can just help me with
that... because I'm going to put this project on my Resume and I want to
complete it as soon as possible.

Waiting for your reply 🙏

**Comment by joshiayush** [comment]
Just pinging you in case you did not notice this mail...

**Comment by thechampagne** [comment]
Hi, I would love to help you but unfortunately I've never tried to generate docs of c code.

**Comment by joshiayush** [comment]
Okay, so can you help me in other ways? Like testing or adding features or
just writing docs manually?

**Pull request merged**
